-- MySQL Script generated by MySQL Workbench
-- Fri Apr 26 20:17:03 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estacionaPP` DEFAULT CHARACTER SET utf8 ;
USE `estacionaPP` ;

-- -----------------------------------------------------
-- Table `estacionaPP`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacionaPP`.`USUARIO` (
  `rut_usu` INT NOT NULL,
  `nom_usu` VARCHAR(45) NOT NULL,
  `ape_usu` VARCHAR(45) NOT NULL,
  `correo_usu` VARCHAR(45) NOT NULL,
  `dir_usu` VARCHAR(45) NOT NULL,
  `fecha_usu` DATE NOT NULL,
  `contr_usu` VARCHAR(45) NOT NULL,
  `id_tipousu` INT NOT NULL DEFAULT 1,
  UNIQUE INDEX `rut_EMPLEADO_UNIQUE` (`rut_usu` ASC) ,
  PRIMARY KEY (`rut_usu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacionaPP`.`CODIGO_QR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacionaPP`.`CODIGO_QR` (
  `id_codqr` INT NOT NULL AUTO_INCREMENT,
  `cont_qr` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_codqr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacionaPP`.`TARIFA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacionaPP`.`TARIFA` (
  `id_tarif` INT NOT NULL AUTO_INCREMENT,
  `nom_tarif` VARCHAR(45) NOT NULL,
  `descr_tarif` VARCHAR(45) NOT NULL,
  `valor_tarif` INT NOT NULL,
  PRIMARY KEY (`id_tarif`),
  UNIQUE INDEX `id_RESERVA_UNIQUE` (`id_tarif` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacionaPP`.`TIPO_PAGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacionaPP`.`TIPO_PAGO` (
  `id_tipopago` INT NOT NULL AUTO_INCREMENT,
  `nom_tipopago` VARCHAR(45) NOT NULL,
  `det_tipopago` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipopago`),
  UNIQUE INDEX `id_tipopago_UNIQUE` (`id_tipopago` ASC) ,
  UNIQUE INDEX `nom_tipopago_UNIQUE` (`nom_tipopago` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacionaPP`.`PAGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacionaPP`.`PAGO` (
  `id_pago` INT NOT NULL,
  `nom_pago` VARCHAR(45) NOT NULL,
  `id_tipopago` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_pago`),
  UNIQUE INDEX `id_pago_UNIQUE` (`id_pago` ASC) ,
  CONSTRAINT `fk_id_tipopago`
    FOREIGN KEY (`id_tipopago`)
    REFERENCES `estacionaPP`.`TIPO_PAGO` (`id_tipopago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacionaPP`.`TIPO_RESERVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacionaPP`.`TIPO_RESERVA` (
  `id_tiporeserv` INT NOT NULL AUTO_INCREMENT,
  `nom_tiporeserv` VARCHAR(45) NOT NULL,
  `descr_tiporeserv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tiporeserv`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `estacionaPP`.`DETALLE_SERVICIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacionaPP`.`DETALLE_SERVICIO` (
  `id_detserv` INT NOT NULL,
  `horainicio_detserv` TIME NOT NULL,
  `horatermino_detser` TIME NOT NULL,
  `duracion_detser` INT NOT NULL,
  `valor_detserv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_detserv`),
  UNIQUE INDEX `id_detserv_UNIQUE` (`id_detserv` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacionaPP`.`SECCION_PLAZA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacionaPP`.`SECCION_PLAZA` (
  `id_seccionplaza` INT NOT NULL AUTO_INCREMENT,
  `nom_seccionplaza` INT NOT NULL,
  PRIMARY KEY (`id_seccionplaza`),
  UNIQUE INDEX `id_plaza_UNIQUE` (`id_seccionplaza` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacionaPP`.`PLAZA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacionaPP`.`PLAZA` (
  `id_plaza` INT NOT NULL AUTO_INCREMENT,
  `num_plaza` INT NOT NULL,
  `est_plaza` TINYINT(1) NOT NULL,
  `id_seccionplaza` INT NOT NULL,
  PRIMARY KEY (`id_plaza`),
  UNIQUE INDEX `id_plaza_UNIQUE` (`id_plaza` ASC) ,
  INDEX `fk_id_seccionplaza_idx` (`id_seccionplaza` ASC) ,
  CONSTRAINT `fk_id_seccionplaza`
    FOREIGN KEY (`id_seccionplaza`)
    REFERENCES `estacionaPP`.`SECCION_PLAZA` (`id_seccionplaza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacionaPP`.`RESERVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacionaPP`.`RESERVA` (
  `id_reserv` INT NOT NULL,
  `fecha_reserv` DATE NOT NULL,
  `hora_reserv` TIME NULL,
  `id_tarif` INT NOT NULL,
  `rut_usu` INT NOT NULL,
  `id_pago` INT NOT NULL,
  `id_tiporeserv` INT NOT NULL,
  `id_detserv` INT NOT NULL,
  `id_codqr` INT NOT NULL,
  `id_plaza` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_reserv`),
  UNIQUE INDEX `id_RESERVA_UNIQUE` (`id_reserv` ASC) ,
  CONSTRAINT `fk_id_tarif`
    FOREIGN KEY (`id_tarif`)
    REFERENCES `estacionaPP`.`TARIFA` (`id_tarif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rut_usu`
    FOREIGN KEY (`rut_usu`)
    REFERENCES `estacionaPP`.`USUARIO` (`rut_usu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_pago`
    FOREIGN KEY (`id_pago`)
    REFERENCES `estacionaPP`.`PAGO` (`id_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_tiporeserv`
    FOREIGN KEY (`id_tiporeserv`)
    REFERENCES `estacionaPP`.`TIPO_RESERVA` (`id_tiporeserv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_detserv`
    FOREIGN KEY (`id_detserv`)
    REFERENCES `estacionaPP`.`DETALLE_SERVICIO` (`id_detserv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_codqr`
    FOREIGN KEY (`id_codqr`)
    REFERENCES `estacionaPP`.`CODIGO_QR` (`id_codqr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_plaza`
    FOREIGN KEY (`id_plaza`)
    REFERENCES `estacionaPP`.`PLAZA` (`id_plaza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacionaPP`.`MODELO_TIPO_AUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacionaPP`.`MODELO_TIPO_AUTO` (
  `id_mod` INT NOT NULL,
  `nom_mod` VARCHAR(45) NOT NULL,
  `tipo_mod` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_mod`),
  UNIQUE INDEX `id_modelo_UNIQUE` (`id_mod` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacionaPP`.`MARCA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacionaPP`.`MARCA` (
  `id_marca` INT NOT NULL AUTO_INCREMENT,
  `nom_marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_marca`),
  UNIQUE INDEX `id_marca_UNIQUE` (`id_marca` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacionaPP`.`AUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacionaPP`.`AUTO` (
  `pat_auto` VARCHAR(6) NOT NULL,
  `id_mod` INT NOT NULL,
  `id_marca` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`pat_auto`),
  UNIQUE INDEX `patenteVehiculo_UNIQUE` (`pat_auto` ASC) ,
  CONSTRAINT `fk_id_mod`
    FOREIGN KEY (`id_mod`)
    REFERENCES `estacionaPP`.`MODELO_TIPO_AUTO` (`id_mod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_marca`
    FOREIGN KEY (`id_marca`)
    REFERENCES `estacionaPP`.`MARCA` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacionaPP`.`USUARIO-AUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacionaPP`.`USUARIO_AUTO` (
  `id_autousu` INT NOT NULL AUTO_INCREMENT,
  `rut_usu` INT NOT NULL,
  `pat_auto` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`id_autousu`),
  CONSTRAINT `fk_rut_usu_auto`
    FOREIGN KEY (`rut_usu`)
    REFERENCES `estacionaPP`.`USUARIO` (`rut_usu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pat_auto`
    FOREIGN KEY (`pat_auto`)
    REFERENCES `estacionaPP`.`AUTO` (`pat_auto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
